# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='caisse.Categorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_achat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantite_vente',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock_actuel',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock_initial',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
