# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0003_auto_20170619_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='modified',
            new_name='updated',
        ),
    ]
