# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0004_auto_20170619_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='created',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
