# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0005_auto_20170619_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='montant_total',
            new_name='montant_total_final',
        ),
    ]
